version: '3.1'

services:
  db:
    container_name: notation
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - 5480:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8070:8080

volumes:
  pgdata:
